In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.naive_bayes import GaussianNB

In [ ]:
data = {'height':[6,5.92,5.58,5.92,5.00,5.50,5.42,5.75],
     'weight':[180,190,170,165,100,150,130,150],
     'foot_size':[12,11,12,10,6,8,7,9],
     'gender':['male','male','male','male','female','female','female','female']}

In [9]:
df_data = pd.DataFrame(data= data)
df_data

   height  weight  foot_size  gender
0    6.00     180         12    male
1    5.92     190         11    male
2    5.58     170         12    male
3    5.92     165         10    male
4    5.00     100          6  female
5    5.50     150          8  female
6    5.42     130          7  female
7    5.75     150          9  female

In [10]:
le = LabelEncoder()

df_data['gender'] = le.fit_transform(df_data['gender'])

In [11]:
display(df_data)

   height  weight  foot_size  gender
0    6.00     180         12       1
1    5.92     190         11       1
2    5.58     170         12       1
3    5.92     165         10       1
4    5.00     100          6       0
5    5.50     150          8       0
6    5.42     130          7       0
7    5.75     150          9       0

In [16]:
corr_matrix = df_data.corr(numeric_only= True)
corr_matrix
corr_matrix['gender'].sort_values(ascending = False)

gender       1.000000
foot_size    0.885422
weight       0.807430
height       0.700746
Name: gender, dtype: float64

In [20]:
splitter = StratifiedShuffleSplit(n_splits = 10, test_size = 0.2, random_state = 42)
strat_splits = []
for train_index, test_index in splitter.split(df_data, df_data["gender"]):
    strat_train_set_n = df_data.iloc[train_index]
    strat_test_set_n = df_data.iloc[test_index]
    strat_splits.append([strat_train_set_n, strat_test_set_n])

In [ ]:
train_set = strat_train_set_n.copy()
attr = train_set.columns
train_set_x = train_set[attr[:len(attr)-1]]
train_set_y = train_set[attr[len(attr)-1:]]

In [ ]:
clf = GaussianNB()
clf.fit(train_set_x, train_set_y)
clf.score(train_set_x, train_set_y)

In [42]:
test_set = strat_test_set_n.copy()
attr = test_set.columns
test_set_x = test_set[attr[:len(attr)-1]]
test_set_y = test_set[attr[len(attr)-1:]]

In [50]:
result = clf.predict(test_set_x)
print(result)
print(test_set_y)

[1 0]
   gender
0       1
6       0

In [56]:
matches = [predicted == y for predicted, y in zip(result, test_set_y.values)]
pd.DataFrame(matches).value_counts()

0
True    2
Name: count, dtype: int64

In [73]:
# Predict New Number
x = pd.DataFrame([[5,100,6]],columns=['height','weight','foot_size'])
predicted = clf.predict(x)
print(f"Predicted Gender: {'Male' if predicted else 'Female'}")

Predicted Gender: Female